### ISSUE TITLE
add gpt-4

### ISSUE THREAD

**Issue by thisisanameforsure** [billxbf/ReWOO#2]
putting gpt-4 as a base model currently throws the error:

Traceback (most recent call last):
  File "repos/ReWOO/run.py", line 88, in <module>
    main(args)
  File "repos/ReWOO/run.py", line 75, in main
    method = PWS_Base(planner_model=args.planner_lm, solver_model=args.sovler_lm,
  File "repos/ReWOO/algos/PWS.py", line 130, in __init__
    super().__init__(available_tools=available_tools,
  File "repos/ReWOO/algos/PWS.py", line 23, in __init__
    self.planner_token_unit_price = get_token_unit_price(planner_model)
  File "repos/ReWOO/utils/util.py", line 40, in get_token_unit_price
    raise ValueError("Model not found")
ValueError: Model not found

**Comment by billxbf** [comment]
Thanks for the advice, I've added `gpt-4` support in this PR https://github.com/billxbf/ReWOO/pull/3
